name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint-checks:
    name: Link Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        id: checkout-source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        id: install-dependencies
        run: npm install

      - name: Lint Check
        id: lint-check
        run: npm run lint

      - name: Super Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ${{ github.workspace }}
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false

  unit-testing:
    needs: lint-checks
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        id: checkout-source
        uses: actions/checkout@v4

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        id: install-dependencies
        run: npm install

      - name: Unit Tests
        id: unit-test
        run: npm run test

  integration-testing:
    needs:
      - lint-checks
      - unit-testing
    name: Integration Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        id: checkout-source
        uses: actions/checkout@v4

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        id: install-dependencies
        run: npm install

      - name: Package dist/
        id: package-dist
        run: npm run package

      - name: Integration Tests
        id: integration-tests
        uses: ./
